Documentation for FIST sampling
smash-transport/smash-vhlle-hybrid pull request #47
Opened 2024-11-20 12:10 UTC by NGoetz

This is an add-on to #45, containing the documentation.  A general section on adding new modules should give an entry point to future developers.

2025-01-13 10:41 UTC, AxelKrypton requested changes
I have suggested some polishing work and some refinements. I am happy to discuss this further, if needed. 😊

2025-01-13 10:41 UTC, AxelKrypton commented on docs/developer/new_module.md
I like the intent of this file! 💪 

I'd refine it in the following way:

1. Use periods at the end of each bullet point. Use one sentence per line, too.
2. I would add e.g. an `info` or `tip` admonition box after the first paragraph to tell the user that the FIST implementation can be looked up to see how to add a new module in the future.
3. `:material-file: _Files_` and `:file_folder: **folders**` in the documentation are written prepending emojis and using italic/bold font. Do it here, too.
4. I would milden the sentence "The following steps are required:" and simply say that the following steps serve as guidance and are probably needed when adding a new module.
5. Maybe it makes it easier to give instructions referring to a concrete module name. You can e.g. say something like: "For the sake of clarity, let's suppose to be interested in adding the `Octopus` software as new afterburner." 😅 OK, you can use `MUSIC` for hydro maybe...
6. I would more "pedagogical" in the steps. I am not sure a reader that did not deal with the code as I did in the PR would understand what you write here. 🤔 Maybe adding a concrete example for each statement would help already, but couples code and documentation too much, IMO. What if we just describe the steps more in an abstract way, like you did for the last points?
7. `[MODULE]` should be `[Module]` I guess.
8. Although not needed, consider adding  a direct link to this page in the developer guide overview page.

2025-01-13 14:14 UTC, NGoetz commented on docs/user/prerequisites.md
> +In principle, the Hybrid handler is agnostic to the physics model used in each state, and is built in a way to support different software with minimal efforts. So far, the following choices exist for
This sounds to me like we can by construction only offer flexibility for some of the stages. But we actually can replace a lot of things, we just haven't implemented it all. How about:

`In principle, the Hybrid handler is agnostic to the physics model used in each state, and is built in a way to support different software with minimal efforts. Currently, this is realized by supporting for the sampling stage:`

2025-01-13 15:24 UTC, NGoetz commented on docs/developer/new_module.md
I am still torn between making it more specific, and the wish to not couple code and documentation.
The way I went now was to add a few small snippets of code. My reasoning was the following: they are small and unlikely to change much anytime, but the next time a module is added, I will probably be not around anymore, so it makes sense to make it as easy accessible as possible. But of course we can also remove them again if you think this is not worth it.

2025-01-16 11:47 UTC, AxelKrypton approved these changes
Excellent work @NGoetz. 👏 I took the freedom to refine around the documentation, I hope you are fine with my changes. If not, speak up. If you agree with them, just go ahead and merge. I will then deploy `develop` documentation.

Ah, I forgot, you need to rebase on `develop` before merging. I do not expect conflicts, though.

2025-01-16 11:58 UTC, merged